//DO NOT EDIT THIS FILE
//THIS IS AN AUTOMATICALLY GENERATED CPP FILE
#include "MQTTParser.h"
{% for filename in filenames %}
#include "{{filename}}"{% endfor %}

void MQTTParser::createAction(const uint8_t led_count){

      Serial.println("Create Action Called");

 {% for action_begin_letter in actionclasses -%}
    {% for actionclass in actionclasses[action_begin_letter] -%}
static const char {{actionclass}}_ACTIONKEY[5] = "{{ actionclasses[action_begin_letter][actionclass]['action_key'] }}";
    {% endfor %}
{%- endfor %}

  //Delete the action if the current stored action was never used.
  if (actionAvailable)
    delete action;
      switch(actionKey[0]){
      {% for action_begin_letter in actionclasses %}
        case '{{ action_begin_letter }}':{
        {% for actionclass in actionclasses[action_begin_letter] -%}
         
         {% if not actionclasses[action_begin_letter][actionclass]['custom_function'] %}
         if (cstrcmp({{actionclass}}_ACTIONKEY, actionKey)){
              action = new {{actionclass}}(led_count, MQTTMessage);
              actionAvailable = true;
              Serial.println("{{actionclass}}");
              break; 
         }
        {% endif %}
        {% if actionclasses[action_begin_letter][actionclass]['custom_function'] %}
         if (cstrcmp({{actionclass}}_ACTIONKEY, actionKey)){
              {{  actionclasses[action_begin_letter][actionclass]['custom_code'] }}
              break; 
         }
        {% endif %}
        {%- endfor %}
        }
      {% endfor %}
      default: {
            break; 
      }
        }

}